console.log("¡Hola Mundo!");
let nombre = "Malinali";
console.log(nombre);
nombre = "Eduardo";
console.log(nombre);
const GRAVEDAD = 9.81;
const PI = 3.141592;
let edad = 29;
let estatura = 1.8;
let gradosCelsius = -10.2;
console.log(edad);
console.log(estatura);
console.log(gradosCelsius);
let mensajeFinal = nombre + " tiene " + edad + " años.";
console.log(nombre + " tiene " + edad + " años.");
let esMayorDeEdad = true;
let tieneTerceraEdad = false;
alert (mensajeFinal);
let nombreMascota = prompt ("Escribe el nombre de tu mascota");
alert ("El nombre de la mascota es : "+ nombreMascota)