alert('Hola');
let valorA = 5;
let valorB = 4;
valorA=9;
console.log(valorA + " + " + valorB + " = " +(valorA + valorB));
console.log(valorA + " + " + valorB + " = " +(valorA - valorB));
console.log(valorA + " + " + valorB + " = " +(valorA * valorB));
console.log(valorA + " + " + valorB + " = " +(valorA / valorB));
console.log("5 % 1 = " + (5 % 1));
console.log("5 % 1 = " + (5 % 2));
console.log("5 % 1 = " + (5 % 3));
console.log("5 % 1 = " + (5 % 4));
console.log("5 % 1 = " + (5 % 5));
let variable1 = 10;
console.log(variable1); 
variable1 += 5;
console.log(variable1);
variable1 -= 7;
console.log(variable1);
variable1 *= 2;
console.log(variable1);
let variable2 = 0;
console.log(variable2);
variable2++;
console.log(variable2);
variable2++;
console.log(variable2);
let variable3 = 5;
console.log(variable3);
variable3--;
console.log(variable3);
variable3--;
console.log(variable3);
console.log("5 == 5 -> " + (5 == 5));
console.log("5 == '5' -> " + (5 == '5'));
console.log("5 === '5' -> " + (5 === '5'));

console.log("18 != 17 -> " + (18 != 17));
console.log("18 != '18' -> " + (18 != '18'));
console.log("18 !== '18' -> " + (18 !== '18'));
let variableMayor = 24;
let variableMenor = -1;
console.log(variableMayor + " > " + variableMenor + " -> " + (variableMayor > variableMenor));
console.log(variableMayor + " < " + variableMenor + " -> " + (variableMayor < variableMenor));

let variableIgual = 24;
console.log(variableMayor + " >= " + variableIgual + " -> " + (variableMayor >= variableIgual));
console.log(variableMayor + " <= " + variableIgual + " -> " + (variableMayor <= variableIgual));